# Simple default config of a 4x4 mesh
# Each parameter is overwritten when corresponding command line value is set
#
# NOC & WIRED CONFIGURATION
#
#
# Topologies:
#   MESH
#   BUTTERFLY
#   BASELINE
#   OMEGA
#
#   BUTTERFLY, BASELINE, and OMEGA are Delta Network topologies
# topology: MESH
# X and Y mesh sizes
mesh_dim_x: 8
mesh_dim_y: 8
# number of flits for each router buffer
buffer_depth: 4
# size of flits, in bits
flit_size: 32
# lenght in mm of router to hub connection
r2h_link_length: 2.0
# lenght in mm of router to router connection
r2r_link_length: 1.0
n_virtual_channels: 1

# Routing algorithms:
#   XY
#   DELTA
#   WEST_FIRST
#   NORTH_LAST
#   NEGATIVE_FIRST
#   ODD_EVEN
#   DYAD
#   TABLE_BASED
# Each of the above labels should match a corresponding
# implementation in the routingAlgorithms source code directory
routing_algorithm: XY
routing_table_filename: ""

# Routing specific parameters
#   dyad_threshold: double
dyad_threshold: 0.6

# Selection Strategies:
#   RANDOM
#   BUFFER_LEVEL
#   NOP
# Each of the above labels should match a corresponding
# implementation in the selectionStrategies source code directory
selection_strategy: RANDOM

#
# WIRELESS CONFIGURATION
#
Hubs:
    defaults:
    # channels from which Hub can receive/transmit
        rx_radio_channels: [0]
        tx_radio_channels: [0]
    # list of node tiles attached to the hub
        attached_nodes: []
    # size of buffers connecting the hub to tiles
        to_tile_buffer_size: 4
        from_tile_buffer_size: 4
    # size of antenna tx/rx
        rx_buffer_size: 4
        tx_buffer_size: 4

# for each hub, the same parameters specified above can be customized
# If not specified, the above default values will be used
# What is usually needed to be customized specifically for each hub is
# the set of nodes that are connected to it. In this simple topology
# we have 4 hubs (0-3) connected to the four nodes of the 2x2
# sub-meshes

#  0  1 | 2  3 | 4  5 | 6  7
#  8  9 | 10 11| 12 13| 14 15
#  -------------------------
#  16 17| 18 19| 20 21| 22 23
#  24 25| 26 27| 28 29| 30 31
#  -------------------------
#  32 33| 34 35| 36 37| 38 39
#  40 41| 42 43| 44 45| 46 47
#  -------------------------
#  48 49| 50 51| 52 53| 54 55
#  56 57| 58 59| 60 61| 62 63

    Hub 0:
      attached_nodes: [ 0, 1, 8, 9 ]
    Hub 1:
      attached_nodes: [ 2, 3, 10, 11 ]
    Hub 2:
      attached_nodes: [ 4, 5, 12, 13 ]
    Hub 3:
      attached_nodes: [ 6, 7, 14, 15 ]
    Hub 4:
      attached_nodes: [ 16, 17, 24, 25 ]
    Hub 5:
      attached_nodes: [ 18, 19, 26, 27 ]
    Hub 6:
      attached_nodes: [ 20, 21, 28, 29 ]
    Hub 7:
      attached_nodes: [ 22, 23, 30, 31 ]
    Hub 8:
      attached_nodes: [ 32, 33, 40, 41 ]
    Hub 9:
      attached_nodes: [ 34, 35, 42, 43 ]
    Hub 10:
      attached_nodes: [ 36, 37, 44, 45 ]
    Hub 11:
      attached_nodes: [ 38, 39, 46, 47 ]
    Hub 12:
      attached_nodes: [ 48, 49, 56, 57 ]
    Hub 13:
      attached_nodes: [ 50, 51, 58, 59 ]
    Hub 14:
      attached_nodes: [ 52, 53, 60, 61 ]
    Hub 15:
      attached_nodes: [ 54, 55, 62, 63 ]

# Transmission channels configuration
# each channel modelizes the transmission over a given frequency that
# can be used by a set of communicating hubs
RadioChannels:
    defaults:
    # data rate in Gb/s affect the number of cycles required for a
    # flit transmission
        data_rate: 16
    # bit error rate (CURRENTLY UNSUPPORTED)
        ber: [0, 0]
    # mac policies:

    # who has the token releas only when a complete packet has
    # been sent
        #[TOKEN_PACKET]

    # who has the token, release only after a fixed number of
    # cycles, even no transmission is occurring
        #[TOKEN_HOLD, num_hold_cycles]

    # who has the token, holds the packet until needed for
    # transmissions, until a max number of cycles is reached
        #[TOKEN_MAX_HOLD, max_hold_cycles]
        mac_policy: [TOKEN_PACKET]


# SIMULATION PARAMETERS
#
clock_period_ps: 500
# duration of reset signal assertion, expressed in cycles
reset_time: 1000
# overal simulation lenght, expressed in cycles
#simulation_time: 500000
simulation_time: 5000000
#10801242 29493122
# collect stats after a given number of cycles
stats_warm_up_time: 100
# power breakdown, nodes communication details
detailed: false
# stop after a given amount of load has been processed
max_volume_to_be_drained: 0
show_buffer_stats: false

# Winoc
# enable wireless, when false, all wireless channel configuration is
# ignored
use_winoc: true
# experimental power saving strategy
use_wirxsleep: false

# Verbosity level:
#   VERBOSE_OFF
#   VERBOSE_LOW
#   VERBOSE_MEDIUM
#   VERBOSE_HIGH
verbose_mode: VERBOSE_OFF

# Trace
trace_mode: false
trace_filename: ""

min_packet_size: 8
max_packet_size: 8
packet_injection_rate: 0.01
probability_of_retransmission: 0.01

# Traffic distribution:
#   TRAFFIC_RANDOM
#   TRAFFIC_TRANSPOSE1
#   TRAFFIC_TRANSPOSE2
#   TRAFFIC_HOTSPOT
#   TRAFFIC_TABLE_BASED
#   TRAFFIC_BIT_REVERSAL
#   TRAFFIC_SHUFFLE
#   TRAFFIC_BUTTERFLY
traffic_distribution: TRAFFIC_TRACE_BASED
# when traffic table based is specified, use the following
# configuration file
traffic_table_filename: "t.txt"
# trace files should have fixed names data0.txt, data1.txt and so on ..
traffic_no_trace_files: 1
# offset for changing the node IDs
traffic_trace_node_offset: 60