# Simple default config of a 4x4 mesh
# Each parameter is overwritten when corresponding command line value is set
#
# NOC & WIRED CONFIGURATION
#
#
# Topologies:
#   MESH
#   BUTTERFLY
#   BASELINE
#   OMEGA
#
#   BUTTERFLY, BASELINE, and OMEGA are Delta Network topologies
# topology: MESH
# X and Y mesh sizes
mesh_dim_x: 8
mesh_dim_y: 8
# number of flits for each router buffer
buffer_depth: 4
# size of flits, in bits
flit_size: 32
# lenght in mm of router to hub connection
r2h_link_length: 2.0
# lenght in mm of router to router connection
r2r_link_length: 1.0
n_virtual_channels: 1

# Routing algorithms:
#   XY
#   DELTA
#   WEST_FIRST
#   NORTH_LAST
#   NEGATIVE_FIRST
#   ODD_EVEN
#   DYAD
#   TABLE_BASED
# Each of the above labels should match a corresponding
# implementation in the routingAlgorithms source code directory
routing_algorithm: XY
routing_table_filename: ""

# Routing specific parameters
#   dyad_threshold: double
dyad_threshold: 0.6

# Selection Strategies:
#   RANDOM
#   BUFFER_LEVEL
#   NOP
# Each of the above labels should match a corresponding
# implementation in the selectionStrategies source code directory
selection_strategy: RANDOM

#
# WIRELESS CONFIGURATION
#
Hubs:
    defaults:
    # channels from which Hub can receive/transmit
        rx_radio_channels: [0]
        tx_radio_channels: [0]
    # list of node tiles attached to the hub
        attached_nodes: []
    # size of buffers connecting the hub to tiles
        to_tile_buffer_size: 4
        from_tile_buffer_size: 4
    # size of antenna tx/rx
        rx_buffer_size: 4
        tx_buffer_size: 4

# for each hub, the same parameters specified above can be customized
# If not specified, the above default values will be used
# What is usually needed to be customized specifically for each hub is
# the set of nodes that are connected to it. In this simple topology
# we have 4 hubs (0-3) connected to the four nodes of the 2x2
# sub-meshes

    0:
      attached_nodes: [0]
    1:
      attached_nodes: [1]
    2:
      attached_nodes: [2]
    3:
      attached_nodes: [3]
    4:
      attached_nodes: [4]
    5:
      attached_nodes: [5]
    6:
      attached_nodes: [6]
    7:
      attached_nodes: [7]
    8:
      attached_nodes: [8]
    9:
      attached_nodes: [9]
    10:
      attached_nodes: [10]
    11:
      attached_nodes: [11]
    12:
      attached_nodes: [12]
    13:
      attached_nodes: [13]
    14:
      attached_nodes: [14]
    15:
      attached_nodes: [15]
    16:
      attached_nodes: [16]
    17:
      attached_nodes: [17]
    18:
      attached_nodes: [18]
    19: 
      attached_nodes: [19]
    20: 
      attached_nodes: [20]
    21: 
      attached_nodes: [21]
    22: 
      attached_nodes: [22]
    23: 
      attached_nodes: [23]
    24: 
      attached_nodes: [24]
    25: 
      attached_nodes: [25]
    26: 
      attached_nodes: [26]
    27: 
      attached_nodes: [27]
    28: 
      attached_nodes: [28]
    29: 
      attached_nodes: [29]
    30: 
      attached_nodes: [30]
    31: 
      attached_nodes: [31]
    32: 
      attached_nodes: [32]
    33: 
      attached_nodes: [33]
    34: 
      attached_nodes: [34]
    35: 
      attached_nodes: [35]
    36: 
      attached_nodes: [36]
    37: 
      attached_nodes: [37]
    38: 
      attached_nodes: [38]
    39: 
      attached_nodes: [39]
    40: 
      attached_nodes: [40]
    41: 
      attached_nodes: [41]
    42: 
      attached_nodes: [42]
    43: 
      attached_nodes: [43]
    44: 
      attached_nodes: [44]
    45: 
      attached_nodes: [45]
    46: 
      attached_nodes: [46]
    47: 
      attached_nodes: [47]
    48: 
      attached_nodes: [48]
    49:     
      attached_nodes: [49]
    50: 
      attached_nodes: [50]
    51: 
      attached_nodes: [51]
    52: 
      attached_nodes: [52]
    53: 
      attached_nodes: [53]
    54: 
      attached_nodes: [54]
    55: 
      attached_nodes: [55]
    56: 
      attached_nodes: [56]
    57: 
      attached_nodes: [57]
    58: 
      attached_nodes: [58]
    59: 
      attached_nodes: [59]
    60: 
      attached_nodes: [60]
    61: 
      attached_nodes: [61]
    62: 
      attached_nodes: [62]
    63: 
      attached_nodes: [63]
    
# Transmission channels configuration
# each channel modelizes the transmission over a given frequency that
# can be used by a set of communicating hubs
RadioChannels:
    defaults:
    # data rate in Gb/s affect the number of cycles required for a
    # flit transmission
        data_rate: 16
    # bit error rate (CURRENTLY UNSUPPORTED)
        ber: [0, 0]
    # mac policies:

    # who has the token releas only when a complete packet has
    # been sent
        #[TOKEN_PACKET]

    # who has the token, release only after a fixed number of
    # cycles, even no transmission is occurring
        #[TOKEN_HOLD, num_hold_cycles]

    # who has the token, holds the packet until needed for
    # transmissions, until a max number of cycles is reached
        #[TOKEN_MAX_HOLD, max_hold_cycles]
        mac_policy: [TOKEN_PACKET]


# SIMULATION PARAMETERS
#
clock_period_ps: 500
# duration of reset signal assertion, expressed in cycles
reset_time: 1000
# overal simulation lenght, expressed in cycles
simulation_time: 10000000
#10801242 29493122
# collect stats after a given number of cycles
stats_warm_up_time: 100
# power breakdown, nodes communication details
detailed: false
# stop after a given amount of load has been processed
max_volume_to_be_drained: 0
show_buffer_stats: false

# Winoc
# enable wireless, when false, all wireless channel configuration is
# ignored
use_winoc: true
# experimental power saving strategy
use_wirxsleep: false

# Verbosity level:
#   VERBOSE_OFF
#   VERBOSE_LOW
#   VERBOSE_MEDIUM
#   VERBOSE_HIGH
verbose_mode: VERBOSE_OFF

# Trace
trace_mode: false
trace_filename: ""

min_packet_size: 8
max_packet_size: 8
packet_injection_rate: 0.01
probability_of_retransmission: 0.01

# Traffic distribution:
#   TRAFFIC_RANDOM
#   TRAFFIC_TRANSPOSE1
#   TRAFFIC_TRANSPOSE2
#   TRAFFIC_HOTSPOT
#   TRAFFIC_TABLE_BASED
#   TRAFFIC_BIT_REVERSAL
#   TRAFFIC_SHUFFLE
#   TRAFFIC_BUTTERFLY
traffic_distribution: TRAFFIC_TRACE_BASED
# when traffic table based is specified, use the following
# configuration file
traffic_table_filename: "t.txt"
# trace files should have fixed names data0.txt, data1.txt and so on ..
traffic_no_trace_files: 1